version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: football-tactics-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./main.py:/app/main.py
      - ./frontend:/app/frontend
    networks:
      - football-tactics-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: football-tactics-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - football-tactics-network

networks:
  football-tactics-network:
    driver: bridge